// react-vmt/src/components/Skills.js
import React from "react";
import reactLogo from "../images/logo192.png";
import nodeLogo from "../images/nodejs.png";
import pythonLogo from "../images/python.jpg";
function Skills() {
  return (
    <div>
      <ul class="skills">
        <li>
          <img alt="React Logo" src={reactLogo} />
        </li>
        <li>
          <img alt="Svelte Logo" src={nodeLogo} />
        </li>
        <li>
          <img alt="Svelte Logo" src={pythonLogo} />
        </li>
      </ul>
    </div>
  );
}

export default Skills;

// viewMyTravels/src/components/Skills.svelte
<script>
  import svelteLogo from "../images/svelteLogo.png";
  import nodeLogo from "../images/nodejs.png";
  import pythonLogo from "../images/python.jpg";
</script>

<div class="tools">
  <a href="/">Home</a>
  <p>
    This page is being built as a way for me to showcase my UI/UX skills, by
    combinining a few different tools
  </p>

  <ul class="skills">
    <li><img alt="Svelte Logo" src={svelteLogo} /></li>
    <li><img alt="Svelte Logo" src={nodeLogo} /></li>
    <li><img alt="Svelte Logo" src={pythonLogo} /></li>
  </ul>
</div>
