// viewMyTravels/src/components/MapWindow.svelte
<script>
  import { Loader } from "@googlemaps/js-api-loader";
  import "../style/style.css";
  // AIzaSyCf3Ti2vqg3FkheXkhAgdFDYf12Ytp5OnA

  const loader = new Loader({
    apiKey: "AIzaSyCf3Ti2vqg3FkheXkhAgdFDYf12Ytp5OnA",
    version: "weekly",
  });
  let map;

  async function initMap() {
    const { Map } = await google.maps.importLibrary("maps");

    map = new Map(document.getElementById("map"), {
      center: { lat: -34.397, lng: 150.644 },
      zoom: 8,
    });
  }

  //   initMap();
</script>

<main>
  <div class="mapWindow" id="map" />
</main>

// react-vmt/src/components/MapWindow.js
import React from "react";
import "../App.css";
import { GoogleMap, useLoadScript, Marker } from "@react-google-maps/api";
function MapWindow() {
  console.log(process.env.REACT_APP_GCP_MAPS_API_KEY);
  const longitude = -105.20575;
  const latitude = 39.66528666666667;
  const { isLoaded } = useLoadScript({
    googleMapsApiKey: process.env.REACT_APP_GCP_MAPS_API_KEY,
  });
  return <div>{isLoaded ? <Map /> : "loading.."}</div>;
}

function Map() {
  return (
    <GoogleMap
      zoom={18}
      center={{ lat: 39.66528666666667, lng: -105.20575 }}
      mapContainerClassName="mapWindow"
      mapTypeId="satellite"
    ></GoogleMap>
  );
}

export default MapWindow;
